name: pearpass
base: core24
version: "1.2.0"
title: PearPass
summary: A secure, decentralized and fully local password manager
description: |
  PearPass is a secure, decentralized password manager powered by Pear Runtime.

  Features:
  - Secure password, identity, credit card, notes, and custom fields storage
  - Cross-device and cross-platform synchronization via P2P
  - Offline access to your credentials
  - Strong encryption for data security
  - Password strength analysis
  - Random password generator
  - Browser extension integration for Chrome, Edge, and Chromium
  - Fully decentralized - your data stays on your devices

grade: stable
license: Apache-2.0
website: https://pass.pears.com
contact: https://github.com/tetherto/pearpass-app-desktop/issues
issues: https://github.com/tetherto/pearpass-app-desktop/issues
source-code: https://github.com/tetherto/pearpass-app-desktop
confinement: strict
layout:
  /usr/lib/aarch64-linux-gnu/webkitgtk-6.0:
    bind: $SNAP/usr/lib/aarch64-linux-gnu/webkitgtk-6.0
  /usr/lib/x86_64-linux-gnu/webkitgtk-6.0:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/webkitgtk-6.0
plugs:
  dot-config-pear:
    interface: personal-files
    write:
      - $HOME/.config/pear

  # Native messaging host directories for browser extension
  chrome-native-messaging:
    interface: personal-files
    write:
      - $HOME/.config/google-chrome/NativeMessagingHosts

  chromium-native-messaging:
    interface: personal-files
    write:
      - $HOME/.config/chromium/NativeMessagingHosts

  edge-native-messaging:
    interface: personal-files
    write:
      - $HOME/.config/microsoft-edge/NativeMessagingHosts

  shmem:
    interface: shared-memory
    private: true

apps:
  pearpass:
    extensions: [gnome]
    command: usr/bin/pear-pass
    common-id: com.pears.pass
    plugs:
      - home
      - network
      - network-bind
      - network-observe
      - dot-config-pear
      - chrome-native-messaging
      - chromium-native-messaging
      - edge-native-messaging
      - shmem
      - unity7
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - gsettings
      - opengl
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib:$LD_LIBRARY_PATH
      # Ensure Pear Runtime can find its config
      PEAR_CONFIG_DIR: $HOME/.config/pear
      # For P2P networking
      NODE_OPTIONS: "--dns-result-order=ipv4first"
      # Disable libproxy to avoid missing libpxbackend-1.0.so errors
      GIO_USE_VFS: local
      GIO_USE_PROXY_RESOLVER: dummy
      GIO_EXTRA_MODULES: /nonexistent

# Support both amd64 and arm64 architectures
platforms:
  amd64:
    build-on: amd64
    build-for: amd64
  arm64:
    build-on: arm64
    build-for: arm64

parts:
  # Local assets (icons, desktop file, etc.)
  local-assets:
    plugin: dump
    source: assets
    source-type: local
    organize:
      icon.png: usr/share/icons/hicolor/256x256/apps/pearpass.png
      snap/gui/pearpass.desktop: usr/share/applications/pearpass.desktop
    prime:
      - usr/share/icons/hicolor/256x256/apps/pearpass.png
      - usr/share/applications/pearpass.desktop

  # Pre-built binary from CDN (arm64 uses local file until CDN is updated with complete archive)
  pearpass-binary:
    after: [local-assets]
    plugin: dump
    source:
      - to amd64: "https://static.tether.dev/pearpass/PearPass.linux.x64.bin.tar.gz"
      - to arm64: "https://static.tether.dev/pearpass/PearPass.linux.arm64.bin.tar.gz"
    source-type: tar
    organize:
      pearpass: usr/bin/pear-pass
      lib: usr/lib
      pear-pass: usr/share/pear-pass

  # WebKitGTK 6.0 (not included in gnome-46-2404 content snap)
  webkit:
    plugin: nil
    stage-packages:
      - libwebkitgtk-6.0-4

  # Fix executable stack flags (security hardening) - only needed for amd64
  execstack:
    after: [pearpass-binary]
    plugin: nil
    build-packages:
      - execstack
    override-prime: |
      if [[ $CRAFT_ARCH_BUILD_FOR = amd64 ]]; then
        execstack -c usr/bin/pear-pass 2>/dev/null || true
      fi