name: pearpass
base: core24
version: "1.3.0"
title: PearPass
summary: A secure, decentralized and fully local password manager
description: |
  PearPass is a secure, decentralized password manager powered by Pear Runtime.

  Features:
  - Secure password, identity, credit card, notes, and custom fields storage
  - Cross-device and cross-platform synchronization via P2P
  - Offline access to your credentials
  - Strong encryption for data security
  - Password strength analysis
  - Random password generator
  - Browser extension integration for Chrome, Edge, and Chromium
  - Fully decentralized - your data stays on your devices

grade: stable
license: Apache-2.0
website: https://pass.pears.com
contact: https://github.com/tetherto/pearpass-app-desktop/issues
issues: https://github.com/tetherto/pearpass-app-desktop/issues
source-code: https://github.com/tetherto/pearpass-app-desktop

# Classic confinement: no sandbox, full system access.
# This allows the app to write native-messaging manifests to ~/.config/*/NativeMessagingHosts
# without needing personal-files plugs or manual snap connect commands.
confinement: classic

apps:
  pearpass:
    # No extensions - classic confinement does not support extensions.
    # Wrapper to restore $HOME to the real home directory (safety measure).
    command: usr/bin/pearpass-launch
    common-id: com.pears.pass
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib:$LD_LIBRARY_PATH
      # Ensure Pear Runtime can find its config
      PEAR_CONFIG_DIR: $HOME/.config/pear
      # For P2P networking
      NODE_OPTIONS: "--dns-result-order=ipv4first"
      # Disable libproxy to avoid missing libpxbackend-1.0.so errors
      GIO_USE_VFS: local
      GIO_USE_PROXY_RESOLVER: dummy
      GIO_EXTRA_MODULES: /nonexistent

# Support both amd64 and arm64 architectures
platforms:
  amd64:
    build-on: amd64
    build-for: amd64
  arm64:
    build-on: arm64
    build-for: arm64

parts:
  # Local assets (icons, desktop file, etc.)
  local-assets:
    plugin: dump
    source: assets
    source-type: local
    organize:
      icon.png: usr/share/icons/hicolor/256x256/apps/pearpass.png
      snap/gui/pearpass.desktop: usr/share/applications/pearpass.desktop
    prime:
      - usr/share/icons/hicolor/256x256/apps/pearpass.png
      - usr/share/applications/pearpass.desktop

  # Launch wrapper (fixes $HOME under snap so native-messaging works)
  launcher:
    plugin: dump
    # snapcraft.yaml lives in ./snapcraft, so local sources are relative to this directory.
    source: launcher
    source-type: local
    organize:
      pearpass-launch: usr/bin/pearpass-launch
    override-prime: |
      craftctl default
      chmod 0755 "$CRAFT_PRIME/usr/bin/pearpass-launch"
    prime:
      - usr/bin/pearpass-launch

  # Pre-built binary from GitHub releases AppImage
  # Downloads AppImage, extracts it, and installs the contents
  pearpass-binary:
    after: [local-assets, launcher]
    plugin: nil
    build-packages:
      - curl
      - file
    override-pull: |
      set -eu

      # Determine architecture-specific AppImage URL
      # Using v1.3.0 release - update version when new releases are available
      RELEASE_VERSION="1.3.0"
      case "$CRAFT_ARCH_BUILD_FOR" in
        amd64) ARCH="x64" ;;
        arm64) ARCH="arm64" ;;
        *) echo "Unsupported architecture: $CRAFT_ARCH_BUILD_FOR"; exit 1 ;;
      esac

      APPIMAGE_URL="https://github.com/tetherto/pearpass-app-desktop/releases/download/v${RELEASE_VERSION}/PearPass-Desktop-Linux-${ARCH}-v${RELEASE_VERSION}.AppImage"

      echo "Downloading AppImage from: $APPIMAGE_URL"
      curl -L -o PearPass.AppImage "$APPIMAGE_URL"
      chmod +x PearPass.AppImage

      echo "Extracting AppImage..."
      ./PearPass.AppImage --appimage-extract

      # Move extracted contents to source directory
      mv squashfs-root/* .
      rm -rf squashfs-root PearPass.AppImage
    override-build: |
      set -eu

      # Install binary
      mkdir -p "$CRAFT_PART_INSTALL/usr/bin"
      cp -a "$CRAFT_PART_SRC/usr/bin/pear-pass" "$CRAFT_PART_INSTALL/usr/bin/"

      # Install native libraries
      mkdir -p "$CRAFT_PART_INSTALL/usr/lib"
      cp -a "$CRAFT_PART_SRC/usr/lib/"*.so "$CRAFT_PART_INSTALL/usr/lib/" 2>/dev/null || true

      # Install app bundle
      mkdir -p "$CRAFT_PART_INSTALL/usr/share/pear-pass"
      if [ -d "$CRAFT_PART_SRC/usr/share/pear-pass" ]; then
        cp -a "$CRAFT_PART_SRC/usr/share/pear-pass/"* "$CRAFT_PART_INSTALL/usr/share/pear-pass/"
      fi
    prime:
      - usr/bin/pear-pass
      - usr/lib/*.so
      - usr/share/pear-pass

  # WebKitGTK 6.0 - bundled for classic confinement since we can't rely on content snaps
  webkit:
    plugin: nil
    stage-packages:
      - libwebkitgtk-6.0-4

  # Fix executable stack flags (security hardening) - only needed for amd64
  execstack:
    after: [pearpass-binary]
    plugin: nil
    build-packages:
      - execstack
    override-prime: |
      if [[ $CRAFT_ARCH_BUILD_FOR = amd64 ]]; then
        execstack -c usr/bin/pear-pass 2>/dev/null || true
      fi
